name: env_paperJMFU
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - netcdf4
  - xarray
  - cartopy
  - shapely
  - scipy
  - tqdm
  - jupyterlab
  - jupyter-panel-proxy